### ISSUE TITLE
1.15.7 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [gopasspw/gopass-jsonapi#107]
👋 it looks like the 1.15.7 release was not completed, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/139463

**Comment by chenrui333** [comment]
cc @dominikschulz

**Comment by chenrui333** [comment]
also relates to https://github.com/Homebrew/homebrew-core/pull/154750

**Comment by dominikschulz** [comment]
This should be obsolete now, I think?

**Comment by chenrui333** [comment]
yeah, closing for now.
