### ISSUE TITLE
No github release for v1.15.14

### ISSUE THREAD

**Issue by project0** [gopasspw/gopass-jsonapi#128]
Looks like the release for 1.15.14 did not work as its missing from github, so we have now a drift between gopass and gopass-jsonapi

**Comment by dominikschulz** [comment]
Oh, sorry. I missed that. Will make sure we get an v1.15.14 tonight.

**Comment by chenrui333** [comment]
@dominikschulz 👋 looks like this is still not done yet? thanks.

**Comment by dominikschulz** [comment]
https://github.com/gopasspw/gopass-jsonapi/releases/tag/v1.15.14
