### ISSUE TITLE
Brave configuration on Windows 11 not working.

### ISSUE THREAD

**Issue by guillermodotn** [gopasspw/gopass-jsonapi#131]
### Summary
Configuring `gopass-jsonapi` for Brave on Windows is not working, but it works using the Chromium configuration.

### Steps To Reproduce
1. Install `gopass` using scoop.
2. Install `gopass-jsonapi` using scoop.
3. Add the Gopass Bridge extension to Brave.
4. Run `gopass-jsonapi configure` and select Brave as the browser.

### Expected Behavior
The configuration for Brave should work with the Brave browser.

### Environment
- **OS Name**: Microsoft Windows 11 Pro  
- **OS Version**: 10.0.22631 N/A Build 22631  
- **Brave Version**: 1.70.117 Chromium: 129.0.6668.59 (Official Build) (64-bit)  
- **gopass Version**: 1.15.14 go1.22.5  
- **gopass-jsonapi Version**: 1.15.13  
- **Installation method**: scoop  
- **Gopass Bridge Version**: 0.9.0

### Additional Context
The Brave configuration doesn't work for `gopass-jsonapi`, but the **Chromium** configuration works perfectly for Brave browser.

**Comment by dominikschulz** [comment]
We are using a [different](https://github.com/gopasspw/gopass-jsonapi/blob/master/internal/jsonapi/manifest/setup_windows.go#L23) registry path for brave on Windows, but I have no idea if that's correct. This is way out of my home turf, I'm neither using Windows nor Brave.

This will need help from someone that's more familiar with those.
