### ISSUE TITLE
Arch AUR Package

### ISSUE THREAD

**Issue by 1995parham** [gopasspw/gopass-jsonapi#15]
I have created an AUR package for gopass-bridge in binary format without the need for being built.

https://aur.archlinux.org/packages/gopass-jsonapi-bin/

**Comment by mastertinner** [comment]
Apparently, there is now also a package in the official Arch repos: https://archlinux.org/packages/community/x86_64/gopass-jsonapi/

**Comment by 1995parham** [comment]
Yes you are right, this is great.
