### ISSUE TITLE
Reports the version incompatible with Gopass Bridge.

### ISSUE THREAD

**Issue by vdrandom** [gopasspw/gopass-jsonapi#2]
When splitting functionality between projects like that, please at least report a semblance of a proper version maybe?

Gopass Bridge complains about gopass-jsonapi version again since it is clearly lower than 1.8.5. And I wouldn't mind that, but no automatic search for hostname happens in this case.
```
> gopass-jsonapi --version
gopass-jsonapi version 0.0.1
```

**Comment by vdrandom** [comment]
Also the fact that new version of gopass stripped of this functionality was released while jsonapi part wasn't looks like a dick move. (At first I thought that's on the package maintainer, but no, it seems like you moved jsonapi into a separate project without actually making a release.)

**Comment by giffels** [comment]
Same here. As a workaround you can set the version to 1.8.5 in https://github.com/gopasspw/gopass-jsonapi/blob/dc7295fcd713f9adf7ba6f2890fad267ff2cd9a7/VERSION#L1

This was not a really sophisticated move, please fix it.

Thanks!

**Comment by dominikschulz** [comment]
@vdrandom Lol. While your complaint is certainly correct, your choice of words is not.
@giffels Sorry for that. I take the blame for not coordinating with the gopassbridge maintainers better, but unfortunately I haven't seen much activity here and I don't feel responsible for gopassbridge or the jsonapi myself - one of the reasons why we did move it.

**Comment by Pharb** [comment]
Thanks for reporting this. Sorry for the rough first steps here in the new repository.
I will try to release the current version so it can be used by gopassbridge (see #3).

**Comment by vdrandom** [comment]
@dominikschulz well I was understood, that's what matters the most. I probably overexaggerated and wasn't polite enough. I apologize for that.

Cheers and thanks. While it is easy enough to fix on one's own by modifying a single file, hopefully less people will have to do that.
