### ISSUE TITLE
Latest release no longer works on xubuntu22.04

### ISSUE THREAD

**Issue by jerger** [gopasspw/gopass-jsonapi#81]
### Summary
Latest release no longer works on xubuntu22.04

### Steps To Reproduce
1. sudo dpkg -i gopass-jsonapi_1.14.3_linux_amd64.deb 
2. gopass-jsonapi -h

-> This program can only be run on AMD64 processors with v3 microarchitecture support.

### Environment
* Fresh installed xubuntu22.04 on virtualbox (guest - linux64/ubuntu settings)

### Additional context
gopass-jsonapi_1.11.1_linux_amd64.deb is working on the same vm, maybe changed sth in your build?

**Comment by dominikschulz** [comment]
Well, it's certainly working on xubuntu 22.04.
But not in your CPU.

We have change some build flags a while ago.

Let us check if we were too eager there.

**Comment by jerger** [comment]
Will be avail for tests :-)

**Comment by dominikschulz** [comment]
I think I have an idea what went wrong here. We didn't use the autorelease workflow for the last release and locally I have always set `GOAMD64=v3`, so it doesn't work for many older CPUs.

The fix should be easy and the next time we should really use the GitHub Action release workflow.
