### ISSUE TITLE
SHA256 sum mismatch between releases of gopasspw/gopass-jsonapi and brew

### ISSUE THREAD

**Issue by arpagon** [gopasspw/gopass-jsonapi#98]
### Summary
I recently noticed a mismatch between the SHA256 sums of the releases of gopasspw/gopass-jsonapi and the ones available through brew. I'm concerned that there may have been a problem with the brew downloads or possibly even a breach in the gopasspw/gopass-jsonapi releases.

I would like to investigate this further to ensure the integrity and security of the gopasspw/gopass-jsonapi releases. Can someone please help me understand what might have caused this issue and how we can resolve it?

Thanks in advance for your help!

https://github.com/Homebrew/homebrew-core/pull/119696#issuecomment-1371850725

### Steps To Reproduce
```
brew install gopass-jsonapi
```
- OS: ubuntu 22.04.1 LTS (Jammy Jellyfish)
- gopass-jsonapi Version: gopass-jsonapi version 1.15.2
- Installation method: brew

**Comment by dominikschulz** [comment]
Yeah, I'm sorry. I messed up the 1.15.2 release and had to re-push it. Unfortunately the homebrew updater was so blazingly fast that it had already picked up the wrong hashsum :/

**Comment by arpagon** [comment]
Nice, Thanks for your quick response.
